# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Semih\Desktop\NYP-GUI\pricePrediction_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 692)
        MainWindow.setMinimumSize(QtCore.QSize(690, 692))
        MainWindow.setMaximumSize(QtCore.QSize(690, 692))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_loadData = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_loadData.setGeometry(QtCore.QRect(20, 20, 651, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_loadData.setFont(font)
        self.groupBox_loadData.setObjectName("groupBox_loadData")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_loadData)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 631, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadData_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadData_btn.setFont(font)
        self.loadData_btn.setObjectName("loadData_btn")
        self.horizontalLayout.addWidget(self.loadData_btn)
        self.dataPath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.dataPath.setObjectName("dataPath")
        self.horizontalLayout.addWidget(self.dataPath)
        self.readData_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.readData_btn.setFont(font)
        self.readData_btn.setObjectName("readData_btn")
        self.horizontalLayout.addWidget(self.readData_btn)
        self.preprocess_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.preprocess_btn.setFont(font)
        self.preprocess_btn.setObjectName("preprocess_btn")
        self.horizontalLayout.addWidget(self.preprocess_btn)
        self.label_preprocess = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_preprocess.setFont(font)
        self.label_preprocess.setText("")
        self.label_preprocess.setObjectName("label_preprocess")
        self.horizontalLayout.addWidget(self.label_preprocess)
        self.groupBox_eda = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_eda.setGeometry(QtCore.QRect(20, 120, 211, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_eda.setFont(font)
        self.groupBox_eda.setObjectName("groupBox_eda")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_eda)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.countplot_cut = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countplot_cut.setFont(font)
        self.countplot_cut.setObjectName("countplot_cut")
        self.verticalLayout.addWidget(self.countplot_cut)
        self.countplot_color = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countplot_color.setFont(font)
        self.countplot_color.setObjectName("countplot_color")
        self.verticalLayout.addWidget(self.countplot_color)
        self.countplot_clarity = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countplot_clarity.setFont(font)
        self.countplot_clarity.setObjectName("countplot_clarity")
        self.verticalLayout.addWidget(self.countplot_clarity)
        self.catplot_cutCarat = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catplot_cutCarat.setFont(font)
        self.catplot_cutCarat.setObjectName("catplot_cutCarat")
        self.verticalLayout.addWidget(self.catplot_cutCarat)
        self.distplot_carat = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.distplot_carat.setFont(font)
        self.distplot_carat.setObjectName("distplot_carat")
        self.verticalLayout.addWidget(self.distplot_carat)
        self.distribution_carat = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.distribution_carat.setFont(font)
        self.distribution_carat.setObjectName("distribution_carat")
        self.verticalLayout.addWidget(self.distribution_carat)
        self.distribution_price = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.distribution_price.setFont(font)
        self.distribution_price.setObjectName("distribution_price")
        self.verticalLayout.addWidget(self.distribution_price)
        self.correlation_matrix = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.correlation_matrix.setFont(font)
        self.correlation_matrix.setObjectName("correlation_matrix")
        self.verticalLayout.addWidget(self.correlation_matrix)
        self.plot_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plot_btn.setFont(font)
        self.plot_btn.setObjectName("plot_btn")
        self.verticalLayout.addWidget(self.plot_btn)
        self.groupBox_split = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_split.setGeometry(QtCore.QRect(240, 120, 431, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_split.setFont(font)
        self.groupBox_split.setObjectName("groupBox_split")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_split)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 411, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.split_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.split_label.setObjectName("split_label")
        self.horizontalLayout_2.addWidget(self.split_label)
        self.split_slider = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.split_slider.setFont(font)
        self.split_slider.setMaximum(100)
        self.split_slider.setSingleStep(5)
        self.split_slider.setProperty("value", 5)
        self.split_slider.setOrientation(QtCore.Qt.Horizontal)
        self.split_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.split_slider.setTickInterval(10)
        self.split_slider.setObjectName("split_slider")
        self.horizontalLayout_2.addWidget(self.split_slider)
        self.split_spinbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.split_spinbox.setMaximum(100)
        self.split_spinbox.setSingleStep(5)
        self.split_spinbox.setProperty("value", 5)
        self.split_spinbox.setObjectName("split_spinbox")
        self.horizontalLayout_2.addWidget(self.split_spinbox)
        self.split_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.split_btn.setFont(font)
        self.split_btn.setObjectName("split_btn")
        self.horizontalLayout_2.addWidget(self.split_btn)
        self.split_succes_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.split_succes_label.setFont(font)
        self.split_succes_label.setText("")
        self.split_succes_label.setObjectName("split_succes_label")
        self.horizontalLayout_2.addWidget(self.split_succes_label)
        self.groupBox_train = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_train.setGeometry(QtCore.QRect(240, 200, 431, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_train.setFont(font)
        self.groupBox_train.setObjectName("groupBox_train")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_train)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 411, 182))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.linear_regression = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.linear_regression.setObjectName("linear_regression")
        self.verticalLayout_2.addWidget(self.linear_regression)
        self.decision_tree = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.decision_tree.setObjectName("decision_tree")
        self.verticalLayout_2.addWidget(self.decision_tree)
        self.random_forest = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.random_forest.setObjectName("random_forest")
        self.verticalLayout_2.addWidget(self.random_forest)
        self.knn = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.knn.setObjectName("knn")
        self.verticalLayout_2.addWidget(self.knn)
        self.train_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_btn.sizePolicy().hasHeightForWidth())
        self.train_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.train_btn.setFont(font)
        self.train_btn.setObjectName("train_btn")
        self.verticalLayout_2.addWidget(self.train_btn)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.train_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.train_label.setFont(font)
        self.train_label.setText("")
        self.train_label.setObjectName("train_label")
        self.verticalLayout_2.addWidget(self.train_label)
        self.groupBox_prediction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_prediction.setGeometry(QtCore.QRect(20, 420, 321, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_prediction.setFont(font)
        self.groupBox_prediction.setObjectName("groupBox_prediction")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_prediction)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 301, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.carat_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.carat_label.setObjectName("carat_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.carat_label)
        self.carat_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.carat_value.setObjectName("carat_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carat_value)
        self.cut_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.cut_label.setObjectName("cut_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cut_label)
        self.cut_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.cut_value.setObjectName("cut_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cut_value)
        self.color_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.color_label.setObjectName("color_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.color_label)
        self.color_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.color_value.setObjectName("color_value")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.color_value)
        self.clarity_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.clarity_label.setObjectName("clarity_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.clarity_label)
        self.clarity_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.clarity_value.setObjectName("clarity_value")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.clarity_value)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.predict_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.predict_btn.setFont(font)
        self.predict_btn.setObjectName("predict_btn")
        self.verticalLayout_3.addWidget(self.predict_btn)
        self.groupBox_results = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_results.setGeometry(QtCore.QRect(390, 420, 281, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_results.setFont(font)
        self.groupBox_results.setObjectName("groupBox_results")
        self.results_area = QtWidgets.QTextEdit(self.groupBox_results)
        self.results_area.setGeometry(QtCore.QRect(10, 20, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.results_area.setFont(font)
        self.results_area.setObjectName("results_area")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(126, 0, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diamond Price Prediction"))
        self.groupBox_loadData.setTitle(_translate("MainWindow", "Load Data"))
        self.loadData_btn.setText(_translate("MainWindow", "Browse"))
        self.readData_btn.setText(_translate("MainWindow", "Read Data"))
        self.preprocess_btn.setText(_translate("MainWindow", "Preprocess Data"))
        self.groupBox_eda.setTitle(_translate("MainWindow", "EDA"))
        self.countplot_cut.setText(_translate("MainWindow", "Countplot (Cut)"))
        self.countplot_color.setText(_translate("MainWindow", "Countplot (Color)"))
        self.countplot_clarity.setText(_translate("MainWindow", "Countplot (Clarity)"))
        self.catplot_cutCarat.setText(_translate("MainWindow", "Catplot (Cut , Carat)"))
        self.distplot_carat.setText(_translate("MainWindow", "Distplot (Carat)"))
        self.distribution_carat.setText(_translate("MainWindow", "Distribution of Carat"))
        self.distribution_price.setText(_translate("MainWindow", "Distribution of Price"))
        self.correlation_matrix.setText(_translate("MainWindow", "Correlation Matrix"))
        self.plot_btn.setText(_translate("MainWindow", "Plot"))
        self.groupBox_split.setTitle(_translate("MainWindow", "Split Dataset"))
        self.split_label.setText(_translate("MainWindow", "Test Size (%) :"))
        self.split_btn.setText(_translate("MainWindow", "Split"))
        self.groupBox_train.setTitle(_translate("MainWindow", "Train Model"))
        self.linear_regression.setText(_translate("MainWindow", "Linear Regression"))
        self.decision_tree.setText(_translate("MainWindow", "Decision Tree"))
        self.random_forest.setText(_translate("MainWindow", "Random Forest"))
        self.knn.setText(_translate("MainWindow", "K-Neighbors Regressor (KNN)"))
        self.train_btn.setText(_translate("MainWindow", "Train"))
        self.groupBox_prediction.setTitle(_translate("MainWindow", "Prediction"))
        self.carat_label.setText(_translate("MainWindow", "Carat : "))
        self.cut_label.setText(_translate("MainWindow", "Cut : "))
        self.color_label.setText(_translate("MainWindow", "Color : "))
        self.clarity_label.setText(_translate("MainWindow", "Clarity : "))
        self.predict_btn.setText(_translate("MainWindow", "Predict"))
        self.groupBox_results.setTitle(_translate("MainWindow", "Results"))
        self.label.setText(_translate("MainWindow", "                  170207021 - Semih ŞEVİK - OOP Final Project"))

